# Generated by Django 4.0.2 on 2022-02-24 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0009_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('f1677982-9f12-49d8-9779-d2c237dcb4cd'), primary_key=True, serialize=False, verbose_name='作者编号'),
        ),
    ]
