# Generated by Django 4.0.2 on 2022-02-24 03:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0010_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('75e67d23-9fff-49b0-a20a-b78676c42ea8'), primary_key=True, serialize=False, verbose_name='作者编号'),
        ),
    ]
